# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a1b9e8f715d15af647352dacf062b748"
name = "shipping-delivery"
handle = "shipping-delivery-2"
application_url = "https://folder-coin-muscles-cst.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shipping-delivery-22.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://folder-coin-muscles-cst.trycloudflare.com/auth/callback",
  "https://folder-coin-muscles-cst.trycloudflare.com/auth/shopify/callback",
  "https://folder-coin-muscles-cst.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
